version: 2.1

jobs:
  docker-lint:
    docker:
     - image: hadolint/hadolint
    steps:
      - checkout
      - run:
          command: |
              #/bin/hadolint --ignore DL3018 - < dockerfiles/Dockerfile
              hadolint --version

workflows:
  version: 2
  test:
    jobs:
      - docker-lint
